src/apps/users/urls.py
# Django
from django.urls import path

# View
from apps.users import views

urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='update/',
        view=views.UpdateUserView.as_view(),
        name='update'
    ),
]

src/cash_flow_reminder/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.home import homePage

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', homePage, name='home'),
    path('user/', include(('apps.users.urls', 'user'), namespace='user')),
    path('bill/', include(('apps.bills.urls', 'bill'), namespace='bill')),
    path('payment/', include(('apps.payments.urls', 'payment'), namespace='payment'))
]

src/templates/base.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block head_content %}VecindApp - Login{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>

    {% block footer %}
      <!-- Footer -->
      <footer class="page-footer font-small pt-4 blue">
        {% if user.is_authenticated %}

        <div class="container">
            <p>you are logged in as - {{ user.get_full_name }}</p>
            {% if not request.path == '/' %}<a href="{% url 'home' %}" class="btn btn-primary btn-lg btn-block active" role="button" aria-pressed="true">Go Home</a>{% endif%}
            <a href="{% url 'user:update' %}" class="btn btn-primary btn-lg btn-block active" role="button" aria-pressed="true">User Update</a>
            <a href="{% url 'user:logout' %}" class="btn btn-primary btn-lg btn-block active" role="button" aria-pressed="true">Sign Out</a>
        </div>
        {% endif %}
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2018 Copyright:
          <a href="https://www.djangoproject.com/"> Powered by Django 2.0</a>
        </div>
        <!-- Copyright -->

      </footer>
      <!-- Footer -->
    {% endblock%}
  </body>
</html>