src/apps/bills/urls.py
# Django
from django.urls import path
# Local
from apps.bills import views

urlpatterns = [
    path(
        route = '',
        view = views.BillListView.as_view(),
        name = 'list'
    ),
    path(
        route = 'detail/<slug:slug>',
        view = views.BillDetailView.as_view(),
        name = 'detail'
    ),
    path(
        route = 'edit/<slug:slug>',
        view = views.BillUpdateView.as_view(),
        name = 'edit'
    ),
    path(
        route = 'delete/<slug:slug>',
        view = views.BillDeleteView.as_view(),
        name = 'delete'
    ),
    # Regular Bills
    path(
        route = 'create-bill/',
        view = views.FixedCreateView.as_view(),
        name = 'create-bill'
    ),
    # Service Bill
    path(
        route = 'create-service-bill/',
        view = views.BillCreateView.as_view(),
        name = 'create-service-bill'
    ),
]

src/apps/users/urls.py
# Django
from django.urls import path

# View
from apps.users import views

urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='update/',
        view=views.UpdateUserView.as_view(),
        name='update'
    ),
]

src/cash_flow_reminder/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.home import homePage

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', homePage, name='home'),
    path('user/', include(('apps.users.urls', 'user'), namespace='user')),
    path('bill/', include(('apps.bills.urls', 'bill'), namespace='bill')),
    path('payment/', include(('apps.payments.urls', 'payment'), namespace='payment'))
]

src/apps/users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy

from .managers import CustomUserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    first_name = models.CharField(
        max_length=12,
        blank=True,
        unique=False
    )
    last_name = models.CharField(
        max_length=12,
        blank=True,
        unique=False
    )
    is_staff = models.BooleanField(
        gettext_lazy('staff status'),
        default=False,
        help_text=gettext_lazy('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        gettext_lazy('active'),
        default=True,
        help_text=gettext_lazy(
            'Designates whether this user should be treated as active. ''Unselect this instead of deleting accounts.'
        ),
    )
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    USERNAME_FIELD = 'email'
    objects = CustomUserManager()

    class Meta:
        verbose_name = gettext_lazy('user')
        verbose_name_plural = gettext_lazy('users')

    def get_full_name(self):
        return self.first_name +' '+ self.last_name

    def get_short_name(self):
        return self.get_full_name()

    def __str__(self):
        return self.email

src/apps/users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from .models import CustomUser


class SignupForm(forms.Form):
    """Sign up form."""

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    def clean_email(self):
        """Username must be unique."""
        email = self.cleaned_data['email']
        email_taken = CustomUser.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = CustomUser.objects.create_user(**data)
        user.save()

src/apps/users/views.py
"""Users views."""

# Django
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
# Local
from .forms import SignupForm
from .models import CustomUser
from apps.bills.models import Bill


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('user:login')

    def get(self, request, *args, **kwargs):
        """Handle GET requests: instantiate a blank version of the form."""
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))
        return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """Login view."""

    redirect_authenticated_user = True
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    # template_name = 'users/logged_out.html'

class UpdateUserView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_user.html'
    model = CustomUser
    fields = ['first_name', 'last_name']

    def get_object(self):
        """Return user."""
        print(self.request.user.pk)
        return self.request.user

    def get_success_url(self):
        """Return to user's profile."""
        return reverse('home')


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""

    template_name = 'users/detail.html'
    slug_field = 'pk'
    slug_url_kwarg = 'pk'
    queryset = CustomUser.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['bills'] = Bill.objects.filter(user=user).order_by('-created')
        return context

src/templates/users/homepage.html
{% extends "base.html" %}

{% block head_content %}CFR Home{% endblock%}

{% block content %}
    <a href="{% url 'bill:list' %}">Show Bills</a>
    

    
{% endblock%}

src/templates/users/login.html
{% extends "base.html" %}

{% block head_content %}
    CFR sign in
{% endblock%}

{% block content %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Your email and password didn't match. Please try again.
        </p>
    {% endif%}

    <form method="POST" action="{% url 'user:login' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="email" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Sign in!</button>

    </form>

    <p class="mt-4">Don't have an account yet? <a href="{% url 'user:signup' %}">Sign up here.</a></p>

{% endblock %}

src/templates/users/signup.html
{% extends "base.html" %}

{% block head_content %}
CFR sign up
{% endblock %}

{% block content %}

    <form action="{% url 'user:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

src/templates/users/update_user.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
Update profile
{% endblock %}

{% block content %}

<div class="container">
    <p>Email: {{ object.email }}</p>
    <form action="{% url 'user:update' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
    </form>
     
</div>

{% endblock %}