src/apps/bills/urls.py
# Django
from django.urls import path
# Local
from apps.bills import views

urlpatterns = [
    path(
        route = '',
        view = views.BillListView.as_view(),
        name = 'list'
    ),
    path(
        route = 'detail/<slug:slug>',
        view = views.BillDetailView.as_view(),
        name = 'detail'
    ),
    path(
        route = 'edit/<slug:slug>',
        view = views.BillUpdateView.as_view(),
        name = 'edit'
    ),
    path(
        route = 'delete/<slug:slug>',
        view = views.BillDeleteView.as_view(),
        name = 'delete'
    ),
    # Regular Bills
    path(
        route = 'create-bill/',
        view = views.FixedCreateView.as_view(),
        name = 'create-bill'
    ),
    # Service Bill
    path(
        route = 'create-service-bill/',
        view = views.BillCreateView.as_view(),
        name = 'create-service-bill'
    ),
]

src/apps/payments/urls.py
# Django
from django.urls import path
# Local
from apps.payments import views

urlpatterns = [
    # Payments URLs
    path(
        route = 'add-to-bill/<slug:bill_slug>',
        view = views.PaymentCreateView.as_view(),
        name = 'add'
    ),
    path(
        route = 'edit/<slug:slug>',
        view = views.PaymentUpdateView.as_view(),
        name = 'edit'
    ),
    path(
        route = 'delete/<slug:slug>',
        view = views.PaymentDeleteView.as_view(),
        name = 'del'
    )
]

src/cash_flow_reminder/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.home import homePage

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', homePage, name='home'),
    path('user/', include(('apps.users.urls', 'user'), namespace='user')),
    path('bill/', include(('apps.bills.urls', 'bill'), namespace='bill')),
    path('payment/', include(('apps.payments.urls', 'payment'), namespace='payment'))
]

src/apps/bills/models.py
# System Imports

# Django Imports
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.db import models
# Local Imports
from apps.users.models import CustomUser


class Bill(models.Model):
    """ Docstring """
    # Foreign Key ------
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        editable=False
    )
    # Foreign Key END ------
    slug = models.SlugField(
        max_length = 6,
        null = True,
        editable=False,
    ) 
    title = models.CharField(
        max_length=50,
    )
    is_automated = models.BooleanField(
        default=False,
    )
    is_active = models.BooleanField(
        default=True,
    )
    min_payment_amount = models.DecimalField(
        default=0,
        max_digits=11,
        decimal_places=2,
        validators = [MinValueValidator(0)]
    )
    max_due_day = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(31)
        ],
        help_text='Service bill: add the max day for this bill to be paid.\nRegular bill: must use the day of start date.'
    )
    grace_days = models.PositiveIntegerField(
        blank=True,
        null=True,
        default=3,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ]
    )
    description = models.TextField(
        blank=True
    )
    # Meta Data
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Fixed(Bill):
    """ Docstring """
    debt_start_date = models.DateField()
    instalments = models.PositiveSmallIntegerField(
        validators = [
            MinValueValidator(0),
            MaxValueValidator(400)
        ],
    )
    total_amount = models.DecimalField(
        max_digits=11,
        decimal_places=2,
        validators=[MinValueValidator(0)]
    )    

src/apps/bills/forms.py
# Django 
from django.utils.translation import gettext as _
from django.utils import timezone
from django import forms
# Local
from .models import Bill, Fixed


def obj_lt_obj_add_error(instance, dicto, key1, key2, msg='%(greater)s is greater than %(less)s'):
    if (key1 in dicto) and (key2 in dicto):
        if (dicto[key1] or dicto[key1] == 0)  and dicto[key2]:
            if dicto[key1] < dicto[key2]:
                instance.add_error(key2, forms.ValidationError(_(msg), code='invalid', params={'greater':dicto[key2], 'less': dicto[key1]}))


class DateInput(forms.DateInput):
    input_type = 'date'


class BillCreateForm(forms.ModelForm):
    """ Docstring """
    class Meta:
        model = Bill
        exclude = ['author', 'slug']

    def clean(self):
        cleaned_data = super().clean()
        
        if cleaned_data['is_automated'] is False and cleaned_data['min_payment_amount'] > 0:
            self.add_error(None, forms.ValidationError(_("Minimum payment amount must be set to 0 if this bill is not Automated."), code='invalid'))
        elif cleaned_data['is_automated'] is True and cleaned_data['min_payment_amount'] == 0:
            self.add_error(None, forms.ValidationError(_("Minimum payment amount must be different than 0 if this bill is Automated."), code='invalid'))
        

class FixedCreateForm(forms.ModelForm):
    """ Docstring """
    class Meta:
        model = Fixed
        exclude = ['author', 'slug']
        widgets = {
            'debt_start_date' : DateInput(),
            'debt_end_date' : DateInput()
        }
    
    def clean(self):
        cleaned_data = super().clean()
        fields_to_check = (
            ("total_amount", "min_payment_amount"),
        )
        for field_pair in fields_to_check:
            obj_lt_obj_add_error(self, cleaned_data, *field_pair)
        
        if not(cleaned_data['debt_start_date'].day == cleaned_data['max_due_day']):
            self.add_error('max_due_day', forms.ValidationError(_("%(great)s, must be equal as the day in %(less)s"), code='invalid', params={'less':cleaned_data['debt_start_date'], 'great': cleaned_data['max_due_day']}))
        
        return cleaned_data

src/apps/bills/views.py
# System 
# Dajngo
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Sum, Min, Max
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView
from django.core.paginator import Paginator
# Local
from apps.bills.models import Bill, Fixed
from apps.payments.models import Payment
from apps.bills.forms import BillCreateForm, FixedCreateForm


class BillListView(LoginRequiredMixin, TemplateView):
    """ Docstring """
    template_name = 'bills/bill_list.html'

    def get_context_data(self, **kwargs):
        context = super(BillListView, self).get_context_data(**kwargs)
        bills = Bill.objects.filter(author=self.request.user)    
        context['bills'] = bills
        return context


class BillDetailView(LoginRequiredMixin, DetailView):
    """ Docstring """
    template_name = 'bills/bill_detail.html'
    context_object_name = 'bill'

    def get_object(self):
        bill = Bill.objects.get(slug=self.kwargs['slug'])
        if bill.author == self.request.user:
            if hasattr(bill, 'fixed'):
                return bill.fixed
            else:
                return bill
        else:
            raise PermissionDenied('Object {} cannot be viewed by {}'.format(bill, self.request.user))
         
    def get_context_data(self, **kwargs):
        # Retrieves the 'super' get_context
        context = super(BillDetailView, self).get_context_data(**kwargs)
        # Queries, Filters and Order all payments attached to the Bill Identified by self.kwargs['slug']
        payments_queryset = Payment.objects.filter(bill__slug=self.kwargs['slug']).order_by('max_payment_date')
        # Creates the Paginator for the previous QS
        paginator = Paginator(payments_queryset, 12)
        # Get the current page of the page
        page = self.request.GET.get('page')
        # Assign that page to the template
        payments = paginator.get_page(page)
        # Load the paginated QS in the context
        context['payments'] = payments
        # Perform aggregate actions on the following QS
        payments_gt_zero = payments_queryset.filter(amount__gt=0)
        payments_extra_info = payments_gt_zero.aggregate(
            Sum('amount'),
            Avg('amount'),
            Min('amount'),
            Max('amount')
        )
        # If previus QS exists return its values, else take every aggregation and turn their values to 0
        payments_extra_info = payments_extra_info if payments_gt_zero.exists() else payments_extra_info.fromkeys(payments_extra_info.keys(), 0)
        # Update the context with the previously parsed data
        context.update(payments_extra_info)
        return context


class BillUpdateView(LoginRequiredMixin, UpdateView):
    """ Docstring """
    success_url = reverse_lazy('bill:list')
    template_name = 'bills/bill_form.html'
    context_object_name = 'bill'

    def get_object(self):
        bill = Bill.objects.get(slug=self.kwargs['slug'])
        if bill.author == self.request.user:
            if hasattr(bill, 'fixed'):
                return bill.fixed
            else:
                return bill
        else:
            raise PermissionDenied('Object {} cannot be edited by {}'.format(bill, self.request.user))
    
    def get_form_class(self):
        obj = self.get_object()
        if hasattr(obj, 'fixed'):
            return FixedCreateForm
        else:
            return BillCreateForm


class BillDeleteView(LoginRequiredMixin, DeleteView):
    """ Docstring """
    success_url = reverse_lazy('bill:list')
    template_name = 'bills/bill_confirm_delete.html'
    context_object_name = 'bill'

    def get_object(self):
        bill = Bill.objects.get(slug=self.kwargs['slug'])
        if hasattr(bill, 'fixed'):
            return bill.fixed
        else:
            return bill

# 'Regular' bill type views - - - - - 
class FixedCreateView(LoginRequiredMixin, CreateView):
    """ Docstring """
    model = Fixed
    success_url = reverse_lazy('bill:list')
    form_class = FixedCreateForm
    template_name = 'bills/bill_create_form.html'

    def form_valid(self, form):
        """ Docstring
            @form2complete = stores the current values typed in the form.
            @form2complete.user = auto populates the user param from the model
                with the current logged user lazy_object.
        """
        form2complete = form.save(commit=False)
        form2complete.author = self.request.user
        form2complete.save()
        return super().form_valid(form)
        

# 'Service' bill type views - - - - - 
class BillCreateView(LoginRequiredMixin, CreateView):
    """ Docstring """
    model = Bill
    success_url = reverse_lazy('bill:list')
    form_class = BillCreateForm
    template_name = 'bills/bill_create_form.html'

    def form_valid(self, form):
        """ Docstring
            @form2complete = stores the current values typed in the form.
            @form2complete.user = auto populates the user param from the model
                with the current logged user lazy_object.
        """
        form2complete = form.save(commit=False)
        form2complete.author = self.request.user
        form2complete.save()
        return super().form_valid(form)

src/templates/bills/bill_confirm_delete.html
{% extends 'base.html' %}
{% block head_content %}CFR - Bill Delete!{% endblock %}

{% block content %}
    <form action="{% url 'bill:delete' bill.slug %}" method="POST">
        {% csrf_token %}
        Are you sure you want to delete "{{ object.title }}" bill?
        <input type="submit" value="Yes" />
        <input type="button" value="Go back!" onclick="history.back()">
        
    </form>
{% endblock %}

src/templates/bills/bill_create_form.html
{% extends 'base.html' %}
{% block head_content %}CFR - Bulletin Create!{% endblock %}

{% block content %}
{% if form.errors %}
<!-- Error messaging -->
<div id="errors">
    <div class="alert alert-danger">
        <p>There were some errors in the information you entered. Please correct the following:</p>
        {{ form.non_field_errors }}
        <ul>
            {% for field in form %}
                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
<!-- /Error messaging -->
{% endif%}
<div class="container">
    {% if not 'service' in request.path %}
    <form action="{% url 'bill:create-bill' %}" method="POST">
    {% else %}
    <form action="{% url 'bill:create-service-bill' %}" method="POST">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Crear</button>
    </form>
</div>
{% endblock %}

src/templates/bills/bill_detail.html
{% extends 'base.html' %}
{% load tz %}

{% block head_content %}CFR - Bill Detail!{% endblock %}

{% block content %}
    <h1>
        Title: {{ bill.title }} 
    </h1>

    {% comment "Current Time Zone Validation"%}
    {% get_current_timezone as TIME_ZONE %}
        <p>{{ TIME_ZONE }}</p>
    {% endcomment %}

    <p>Active: {{ bill.is_active }} | Automated: {{ bill.is_automated }} </p>
    <p>Created - {{ bill.created|date:"Y-m-d \a\t H:i" }} Last Time Modified - {{ bill.modified|date:"Y-m-d \a\t H:i" }}</p>


    <h5>Max Due Day: {{ bill.max_due_day }}</h5>
    <h5>Grace Days: {{ bill.grace_days }}</h5>
    {% if bill.is_automated %}
        <h5>Min Amount: {{ bill.min_payment_amount }}</h5>
    {% endif %}
    <!-- Fixed Section -->
    {% if bill.fixed %}
        {% localtime on %}
        <h5>Debt Start: {{ bill.fixed.debt_start_date }}<h5>
        {% endlocaltime %}

        <h5>Total Amount: {{ bill.fixed.total_amount }}<h5>
        <h5>Min Amount: {{ bill.min_payment_amount }}</h5>
        <h5>Instalments: {{ bill.fixed.instalments }}</h5>    
    {% endif %}
    {%if bill.description%}
        <h5>Description: {{ bill.description }}</h5>
    {% endif %}
    <br>
    <br>
    <p><b>Toal paid:</b> {{amount__sum}}
        <b>Average:</b> {{amount__avg}}
    </p>
    <h2>PAGOS</h2>
    <a href="{% url 'payment:add' bill_slug=bill.slug %}">Agregar Pago</a>
    <br>
    {% for payment in payments %}
        <p>
            <b>ID:</b> {{payment.slug}} - 
            <b>Amount Paid:</b> {{payment.amount}} - 
            <b>Due Date:</b> {{payment.max_payment_date}} 
            | <a href="{% url 'payment:edit' payment.slug %}">Editar Pago</a>
            | <a href="{% url 'payment:del' payment.slug %}">Eliminar Pago</a>
        </p> 
    {% empty %}
        <p>
            No payments yet done.
        </p>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if payments.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ payments.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ payments.number }} of {{ payments.paginator.num_pages }}.
            </span>
            {% if payments.has_next %}
                <a href="?page={{ payments.next_page_number }}">next</a>
                <a href="?page={{ payments.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

src/templates/bills/bill_form.html
{% extends 'base.html' %}
{% block head_content %}CFR - Bill Update!{% endblock %}

{% block content %}
{% if form.errors %}
<!-- Error messaging -->
<div id="errors">
    <div class="alert alert-danger">
        <p>There were some errors in the information you entered. Please correct the following:</p>
        {% for err in form.non_field_errors %}
        {{ err }}
         {% endfor %}
        <ul>
            {% for field in form %}
                {% if field.errors %}<li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
<!-- /Error messaging -->
{% endif %}
<div class="container">
    <form action="{% url 'bill:edit' bill.slug %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Update</button>
    </form>
</div>
{% endblock %}

src/templates/bills/bill_list.html
{% extends 'base.html' %}
{% block head_content %}CFR - Bill List!{% endblock %}

{% block content %}
<div class="container">
    <h2 class="text-center">Bills</h2>
    <p>
        <a href="{% url 'bill:create-bill' %}">Add Bill</a> |
        <a href="{% url 'bill:create-service-bill' %}">Add Service Bill</a> 
    </p>
    <ul>
    {% for bill in bills %}
        {% if bill.is_active %}
            <li>
                <p>{{ bill.title }}</p>
                <p>
                    <a href="{% url 'bill:detail' bill.slug %}">Detail</a>
                    | <a href="{% url 'bill:edit' bill.slug %}">Edit</a>
                    | <a href="{% url 'bill:delete' bill.slug %}">Delete</a>
                    {% if bill.fixed %}
                        <h5>FACTURA</h5>
                    {% else %}
                        <h5>SERVICE</h5>
                    {% endif %}
                </p>
            </li>
        {% endif %}
    {% empty %}
        <h5>No Bills have been added</h5>
    {% endfor %}
    </ul>
    
</div>
{% endblock %}